### ISSUE TITLE
line/column numbers

### ISSUE THREAD

**Issue by alawatthe** [KoryNunn/parcss#8]
Is there a way to get line/column numbers for all the tokens? The ```index``` property exists only for some tokens. And it is not too useful: I am doing static code analysis and saying there is an error at index 15 is not as useful as saying the error is in line 2 column 5.

I'd like it, if every token had something like:
```js
position: {
    start: {
        line: 2,
        column: 0
    },
    end: {
        line: 2,
        column: 19
    }
},
```

**Comment by KoryNunn** [comment]
Have a look at this function in parse.js: https://github.com/KoryNunn/parcss/blob/master/parser.js#L3

All lexed tokens have an index property that defines where they begin in the source.
They also have a .sourceRef property that has an object with information about the source.

You should be able to use this information to figure out the line number like so:

```javascript
function getLineAndColumn(token){

    var sourceBefore = token.sourceRef.source.slice(0, token.index),
        lineNumber = sourceBefore.match(/\n/g).length,
        column = token.index - sourceBefore.lastIndexOf('\n') - lineNumber;

    console.log(sourceBefore.lastIndexOf('\n'));

    return [lineNumber, column];
}

var source = "function getLineAndColumn(token){\n    var sourceBefore = token.sourceRef.source.slice(0, token.index),\n        lineNumber = sourceBefore.match(/\n/g).length,\n        column = token.index - sourceBefore.lastIndexOf('\n');\n}";

var token = {
    source: 'sourceBefore',
    index: 126,
    sourceRef:{
        source: source
    }
}

getLineAndColumn(token);
```

**Comment by alawatthe** [comment]
Ah, my choice of the word "token" wasn't too good apparently, since parcss also produces a list of tokens.

So with "token" I meant "node in the abstract syntax tree" as produced by 

```js
var ast = parcss.parse(parcss.lex(source));
```

Not every node in the ast has the index property. For example
```css
div {
    color: red;
}
```

produces

```js
[
  {
    "type": "block",
    "content": [
      {
        "type": "statement",
        "property": "color",
        "valueTokens": [
          {
            "type": "word",
            "source": "red",
            "length": 3,
            "index": 15
          }
        ]
      }
    ],
    "selectors": [
      "div"
    ]
  }
]
```

So the "red"-node is the only one with the ```index```-property and thus the only one we can (easily) get position information. So to determine the position of "div" I need to go the the token list, find the "red"-token via the index-property, then go back in the token list until I find the div and use the function you posted to get the line/column numbers... Which is a bit too complicated I think.

But I will close this issue since I saw now what is and isn't possible.

**Comment by KoryNunn** [comment]
I may be able to add source information into parse output, but without looking at it I'm going to assume that it wouldn't be trivial. If I do I'll let you know.
